[OOPOOD-2021-fall] hw5
IgorOzherelev/tank-software-design pull request #6
Opened 2021-10-28 17:35 UTC by IgorOzherelev

2021-11-08 22:19 UTC, a-ivanov requested changes

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/models/movable/LibGdxTank.java
> +public class LibGdxTank extends AbstractLibGdxMovableObject {
У танка не должно быть ничего от LibGdx в названии. Это может быть у графического класса, если он рисуется ее средствами.

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/models/objects/GameObject.java
> +public class GameObject implements Colliding {
Не стоит переусердствовать при разбиении логики между классами. Достаточно (уже обсуждали на лекциях) по классу на:
- логику (танк перемещается между клетками, проверка коллизий; препятствие проверяется на коллизии)
- графику (танк перемещается по экрану, препятствие рисуется на одном и том же месте).

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/models/movable/Movable.java
> +    void prepareForMove(Direction direction);
Слишком много деталей реализации в публично апи. Им сложно пользоваться. Тут явно многое - методы реализации.

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTreesRendererService.java
> +public class LibGdxTreesRendererService implements RendererService {
Не надо разбивать все на "сервисы". Достаточно для простоты вызывать релевантные методы в классе Level (уровень делегирует вызов методов tick для своих логических объектов)/LevelRenderer (вызывает сначала отрисовку клеток, потом танков/препятствий).

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTanksRendererService.java
> +    public List<? extends Movable> getTanks() {
Создавайте геттеры только когда они реально нужны, всегда стоит писать код без них, чтобы логика работы с данным оставалась в private методах класса.

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/gamestate/AwesomeAiGameStateService.java
> +public class AwesomeAiGameStateService implements AiGameStateService<GameState> {
Не вижу интерфейс для создания уровня и две реализации: случайное расположение и чтение из файла. Для этого еще должен быть класс для уровня с логическими объектами, чтобы его можно было создавать.

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +public interface CustomAiService {
Нет, по заданию не должно быть явных интерфейсов, говорящих об использовании сторонней библиотеки. У вас должен появиться интерфейс AIController, с реализацией отправки случайных движений ботов. Далее в 5 дз вам необходимо написать адаптер. Не вижу ни того, ни другого.

2021-11-08 22:19 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/commands/BotsCommandExecutorService.java
> +public class BotsCommandExecutorService implements CommandExecutorService {
Тут должна быть логика отправки команд ботам. Далее по 5 дз необходимо написать еще одну имплементацию этого интерфейса-адаптер, который будет получать рекомендации, переводить их в команды и отправлять ботам.

2021-11-09 04:09 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/gamestate/AwesomeAiGameStateService.java
> +public class AwesomeAiGameStateService implements AiGameStateService<GameState> {
Создание уровня реализовано в пакете generator

2021-11-09 04:25 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +public interface CustomAiService {
В этом пакете реализован интерфейс для обычного ai, и вроде бы реализован адаптер для стороннего: `Awesome AICustomService`. В нем содержится поле с внешним ai, сам класс реализует интерфейс `CustomAIService`; разве адаптер может быть только с наследованием, которое по лекциям плохо?

2021-11-09 04:36 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/commands/BotsCommandExecutorService.java
> +public class BotsCommandExecutorService implements CommandExecutorService {
Что вы имеете в виду под отправкой команд ботам? Сейчас сделаю так: каждой команде прописывается бот, команды рекомендуется от ai сервисов, здесь они вызываются

2021-11-09 05:17 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTanksRendererService.java
> +    public List<? extends Movable> getTanks() {
Ну, так он используется в `LibGdxLevelRendererService`

2021-11-09 05:30 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/objects/GameObject.java
> +public class GameObject implements Colliding {
То есть получается, что движение будет завязано на графику?

2021-11-09 11:21 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/models/objects/GameObject.java
> +public class GameObject implements Colliding {
Так нет же, в классе с движением - нет ссылки на графику. В классе с графикой - есть ссылка на движение. Итого графика завязана на логику (движение).

2021-11-09 11:23 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTanksRendererService.java
> +    public List<? extends Movable> getTanks() {
LibGdxLevelRendererService (переименуйте) должен делегировать отрисовку LibGdxTanksRendererService, не вызывать геттеры из него. Иначе сама логики отрисовки танка - в LibGdxLevelRendererService, а не в LibGdxTanksRendererService.

2021-11-09 11:24 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/gamestate/AwesomeAiGameStateService.java
> +public class AwesomeAiGameStateService implements AiGameStateService<GameState> {
Понял, см. замечания там.

2021-11-09 11:28 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/generator/MapGenerator.java
> +    GameObjectStorage generate();
Возвращайте Level, промежуточные бесполезные классы не нужны.

2021-11-09 11:28 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +public interface CustomAiService {
Понял, да, похоже на правду. CustomAiService - плохое название, это должен быть единственный источник команд для игрока/ботов, тогда так и называйте его, например TankController.

2021-11-09 11:30 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +    void setDeltaTime(float deltaTime);
Если deltatime нужен в recommend, передавайте его туда аргументом, не создавайте мутирующих апи (которые можно забыть вызвать).

2021-11-09 11:30 UTC, a-ivanov commented on src/main/java/ru/mipt/bit/platformer/services/commands/BotsCommandExecutorService.java
> +public class BotsCommandExecutorService implements CommandExecutorService {
Да, было непонятно с CustomAiService, см. замечания к нему.

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/movement/TileMovementService.java
> +public interface TileMovementService {
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/movable/AbstractLibGdxMovableObject.java
> +    protected LibGdxGraphicObject libGdxGraphicObject;
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxLevelRendererService.java
> +public class LibGdxLevelRendererService implements RendererService {
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/movement/TileMovementService.java
> +public interface TileMovementService {
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/movable/AbstractLibGdxMovableObject.java
> +    protected LibGdxGraphicObject libGdxGraphicObject;
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/movable/LibGdxTank.java
> +public class LibGdxTank extends AbstractLibGdxMovableObject {
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/objects/GameObject.java
> +public class GameObject implements Colliding {
Исправлено

2021-11-12 21:18 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/models/movable/Movable.java
> +    void prepareForMove(Direction direction);
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTreesRendererService.java
> +public class LibGdxTreesRendererService implements RendererService {
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/renderers/LibGdxTanksRendererService.java
> +    public List<? extends Movable> getTanks() {
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/gamestate/AwesomeAiGameStateService.java
> +public class AwesomeAiGameStateService implements AiGameStateService<GameState> {
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +public interface CustomAiService {
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/commands/BotsCommandExecutorService.java
> +public class BotsCommandExecutorService implements CommandExecutorService {
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/generator/MapGenerator.java
> +    GameObjectStorage generate();
Исправлено

2021-11-12 21:19 UTC, IgorOzherelev commented on src/main/java/ru/mipt/bit/platformer/services/ai/CustomAiService.java
> +    void setDeltaTime(float deltaTime);
Исправлено

2022-01-30 09:34 UTC, merged